[#15/#16] 실시간 채팅 통신 및 이미지 업로드 구현
kjheee/debus pull request #17
Opened 2024-04-22 11:01 UTC by k-jeonghee

Query Key 관리 방법의 변경으로 전체적으로 관련 코드를 개선하고, 이미지 업로드 기능을 이슈로 분리 후 함께 PR 올립니다!😃

## PR 타입
- [X] 기능 추가
- [X] 코드 개선

## 작업 내용
1. TanStack-Query key 관리 방법 변경
   - `mutations` / `queries` 폴더 분리 후 커스텀훅 작성
   - `factory` 방식을 이용해 `Query Key` 관리 
2. 채팅 메시지 전송 및 실시간 조회 기능 구현
3. 이미지 업로드 기능 구현
	- 업로드 중 버튼을 로딩 스피너로 표시
4. 메시지 스타일 조정

## 설명
1. `mutation - invalidateQueries`적용 후 발신자의 화면만 업데이트 되고 상대방의 채팅방은 적용되지 않는 문제
    **해결**: 전체 메시지를 렌더링하는 `ChatPanel` 컴포넌트에서 `useEffect` 에 `refetch` 적용
2. 채팅방 렌더링 시 `SidePanel`과 `ChatPanel`이 함께 렌더링 되어 부모 Page 컴포넌트(Line)에서 **Suspense**로 감싸고, `useSuspenseQuery` 적용
3. 메시지 내용은 텍스트 or 이미지가 될 수 있어 `Message` 타입 속성의 `file`과 `content`을 옵셔널로 지정
	- 입력된 데이터 타입에 따라 메시지 객체를 생성하도록 `createMessage`함수 분리
	- 이미지 외 다른 파일 형식을 고려해 속성명을 `file`로 표현
1. 레이아웃 유지를 위해 업로드 버튼을 `form` 태그 내부에 두고 참조하는 `input`은 외부에 선언
2. 업로드 함수를 분리하면서 이미지 `url`을 받기 위해 `uploadImage`함수가 `Promise`를 반환하도록 작성

## 채팅방 컴포넌트 구조
![15번이슈](https://github.com/k-jeonghee/debus/assets/93242226/04b55d9f-f4a4-43b7-9518-1b24a20544ed)

## 실행화면
https://github.com/k-jeonghee/debus/assets/93242226/52f6a471-608c-4c97-b746-53d06c02673f

## 관련 이슈
close #15 #16

## 전달사항
1. 메시지 전송을 구현하면서 이미지 업로드 기능을 함께 작업했어요.
2. 컴포넌트 관계를 보시기 편하도록 레이아웃 구조 이미지를 첨부했어요.

2024-04-22 23:09 UTC, bigsaigon333 commented
오늘 밤에 봐볼게요!!!

2024-04-27 06:08 UTC, bigsaigon333 commented on src/api/firebase.ts
> +// ref(db, `users/${user.uid}`)
```suggestion
```
삭제해도 되는 주석이겠죠..?

2024-04-27 06:49 UTC, bigsaigon333 requested changes
정희님 고생하셨습니다~~

일단 눈에 띄는거 위주로 코멘트 몇개 남겨보았으니 확인 부탁드려요!

코드 일부분이 아니라 전반적으로 말씀드리고 싶은거를 조금 적어보면..

1. prettier 의 `tabWidth`를 2로 설정해주세요. 이것은 FE 국룰입니다.. ㅎㅎ 
https://prettier.io/docs/en/option-philosophy <-- 시간되시면 한번 읽어보세용~
2. PR 본문에 상세하게 설명해주신거 보았는데요~ 코드 자체에 코멘트를 달아주시면 더 좋을거 같아요!
어떤 점을 신경써서 코드를 작성하였는지, 어떤 고민이 있었는지, 어떤 reference를 찾아보았는지, 어떤 점을 중점적으로 코드리뷰를 받고 싶은지 등이요~
고민하신 부분을 먼저 말씀해주시면 저도 더 많은 피드백을 드릴 수 있을거 같아요~
예를 들어,, 제가 firebase 쪽은 잘 몰라서 정말 대충 훑었는데요, 요 부분에서 고민하신 점이나 개선하고 싶으신 부분이 있다면 그런 걸 적어주시면, 제가 firebase를 공부를 해서라도 말씀을 드릴게요 ㅎㅎ
(아니면 일반적인 api 통신의 관점에서라도 말씀드릴 수 있을거 같아요!)
3. 강조하고 싶은 점은... 코드 리뷰는 숙제 검사가 아닙니다. 그냥 리뷰어와 리뷰이의 커뮤니케이션 도구에 불과해요. 제가 하는 말이 다 맞는게 아니고, 저도 제안을 드리는 것 뿐입니다. 그러니 무조건적으로 수용하지 마시고, 정희님의 생각을 충분히 말씀해주세요. 참고해본 외부 reference 같은것도 막 첨부하셔도 좋고요~ 서로의 생각을 맞춰서 좋은 코드가 될 수 있게 잘 해봐요 😄

2024-04-27 06:49 UTC, bigsaigon333 commented on src/api/firebase.ts
> +// ref(db, `users/${user.uid}`)
```suggestion
```

요 주석은 없어도 되는거겠죠..?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/api/firebase.ts
> +            }
이 코드만 보았을 때, messages는 배열이므로 `if (messages)` 는 항상 true가 되므로 의미없는 조건문인거 같이 보여요..!

if 문을 추가해야만 했던 상황이 있었던걸까요?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/SidePanel/SidePanel.tsx
> +const SidePanel = ({ id }: { id: string }) => {
사소한 것이지만, `id` 는 너무 모호한 props명인거 같아요

제일 처음에 `<SidePanel id={id} />` 와 같은 코드를 보았을 때,
이 id는 무엇의 id일까? html의 id 속성일까? 등 많은 생각이 떠올랐어요
코드를 보다보니 `roomId` 인 것 같은데, SidePanel 이라는 컴포넌트명에서 room(채팅방)의 id라는 걸 바로 유추해내기가 저는 쉽지 않았어요 ㅠ (제가 지금 이 코드/도메인에 익숙하지 않기 때문인 것도 있을거에요)

조금더 구체적인 명칭으로 지어주시면 의미를 유추하는데 더 도움이 될 거 같아요!

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/SidePanel/SidePanel.tsx
> +    }
이게 렌더링되는 상황이 있을까요? 

useChatRoomQuery가 useSuspenseQuery를 사용하면서, Suspense에 fallback이 렌더링되니까 저는 없을거 같은데요..?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/SidePanel/SidePanel.tsx
> +    }
요것도요..! ErrorBoundary로 에러를 캐치해야하지 않을까요?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/ChatPanel/ChatPanel.tsx
> +    const messages$ = data.map((message) => <ChatMessage key={message.id} message={message} />);
요 `$` 컨벤션은 어디서 온건가요..?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/ChatPanel/ChatPanel.tsx
> +};
```suggestion
  return (
    <div className={cx("container")}>
      <div className={cx("chat-message-container")}>
        {data.map((message) => (
           <ChatMessage key={message.id} message={message} />
        ))}
      </div>
      <ChatForm />
    </div>
  );
};
```

이런 간단한 것은 return 값 안에 같이 jsx로 써주는게 저는 더 읽기 편하다고 생각해요!

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/SidePanel/SidePanel.tsx
> +    assert(chatRoom !== undefined, '채팅방 정보가 존재하지 않습니다.');
chatRoom이 undefined 인 상황이 존재하나용?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/hooks/services/mutations/chat.ts
> +        onSuccess: (id) => navigate(`/lines/${id}`),
mutation 종료후에 route를 이동한다는건 UI 레이어에서 처리해야하는 로직인데,
hooks(mutation) 레이어에 존재해서 어색하게 느껴져요.

mutation의 옵션들을 인자로 받도록 한다음에, 사용하는 곳에서 onSuccess를 할당하도록 바꿔보면 어떨까요?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/hooks/services/queries/chat.ts
> +    );
queryKey factory패턴은 저희 회사에서는 선호되지 않는 패턴인거 같아요. 
의외로 `['chatRooms']` 가 공용이라는 것을 전역으로 사용하는 경우가 잘 없더라고요..? 
물론 지금처럼 queryKey factory를 쓰는건 좋지만, 
모듈 외부와 소통할 땐 queryOptions로 하면 어떨까요?

예를 들면, queryOptions를 별도로 선언하고, 그것을 `useChatRoomQuery`에서 사용하는 식으로요~!


```tsx
const chatRoomQueryOptions = (chatRoomId: string, options) =>   queryOptions({
            queryKey: [chatRooms, chatRoomId],
            queryFn: () => getChatRoom(chatRoomId),
            staleTime: 5 * 1000,
            ...options
        });


// 다른 곳 어디에서 chatRoom을 refetch 하려고 할 때

const queryClient = useQueryClient();

queryClient.refetchQueries(chatRoomQueryOptions("abcd"));  // 대충 쓴거라서 동작하는지는 확인 부탁드려요 ㅎㅎ
```

(options 타입은 귀찮아서 생략했는데 잘 써보세용 ㅎㅎ.. 제네릭도 한번 붙여봐도 좋고용~)

2024-04-27 06:49 UTC, bigsaigon333 commented on src/hooks/services/queries/chat.ts
> +export const useChatRoomQuery: (chatRoomId: string) => UseSuspenseQueryResult<ChatRoomInfoType> = (
이름을 `useChatRoomQuery` 와 같이 `-Query` 를 붙인거 저는 매우 좋다고 생각해요!

그리고 추가적으로 `useChatRoom`과 같은 hook도 만드는걸 저는 선호해요!

```tsx
export const useChatRoom = (chatRoomId: string) => useChatRoomQuery(chatRoomId).data;


```

이렇게 하나의 레이어를 더 추가하면, 컴포넌트 측에서는 이게 react-query를 쓰는지 jotai를 쓰는지 아예 모르게 할 수 있어요.
`Suspense`의 장점중에 하나로 꼽히는 data-fetching layer를 framework-agnostic 하게 쓸 수 있다는 점입니다!!
(일부러 좀 어려운 단어를 써봤는데.. 구글링한번 해보시고 모르겠으면 다시 질문 주세용~)

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/ChatRooms.tsx
> +            {renderModal()}
`renderModal()` 이 꼭 여기 있어야 하나요?

`ModalProvider`아래에 들어갈 수는 없을까요?

2024-04-27 06:49 UTC, bigsaigon333 commented on src/components/Chat/ChatRooms.tsx
> +        }
유저가 인지하여서 어떤 추가적인 액션을 해야하는지 안내하는 방향이 되어야 할거 같아요!

요런건 나중에 다 바꾸실꺼죠? 😄

2024-04-29 09:09 UTC, kjheee reviewed
## 개선사항
1. tabWidth 변경
2. Firebase API: 불필요한 주석 및 분기 제거
3. SidePanel - useSuspenseQuery 사용으로 필요하지 않는 상태 처리 코드 제거
4. props명 수정
5. message 컴포넌트 렌더링 인라인으로 작성
6. TanStack-Query queryOptions 분리 및 훅 캡슐화
7. hook에서 처리하던 라우팅 로직 컴포넌트에서 처리하도록 개선

2024-04-29 09:09 UTC, kjheee commented on src/api/firebase.ts
> +            }
왜 작성했는지 확인해보면서 `onChildAdded` 사용법을 제대로 모르고 있었다는 걸 알게되었어요! 
이해한 뒤에 불필요한 코드를 제거하고 필요한 `callback`만 남기는 것으로 개선했습니다!

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/ChatPanel/ChatPanel.tsx
> +    const messages$ = data.map((message) => <ChatMessage key={message.id} message={message} />);
예시로 제안 받은 코드에서 제거하지 못했어요..! 인라인으로 변경하여 코드를 제거했습니다!

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/SidePanel/SidePanel.tsx
> +    }
기존에 useQuery를 쓰면서 남아있던 코드를 미처 제거하지 못했어요 😅

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/ChatRooms.tsx
> +        }
넵! toast를 도입해서 전체적으로 에러 처리를 개선해보려고 합니다!

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/SidePanel/SidePanel.tsx
> +const SidePanel = ({ id }: { id: string }) => {
props명을 중복에만 집중해서 작성했던 것 같아요
해당 컴포넌트에서 쓰는 id는 채팅방뿐이라는 것을 당연한 것처럼 작성했네요! 
중복보다 명확한 의미를 표현할 수 있도록 신경쓰겠습니다🔥

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/ChatRooms.tsx
> +          onSuccess: (chatRoomId: string) => navigate(`/lines/${chatRoomId}`),
- mutate가 받는 인자를 넘겨서 onSuccess를 반환하도록 고민을 해보았는데 useMutation의 onSuccess 옵션을 반환하는 방법을 찾지 못했어요.. 대신 mutate의 2번째 인자 옵션을 활용해 컴포넌트 내에서 라우팅 로직을 처리할 수 있도록 해보았습니다!
- mutate 함수를 별도 이름을 지정해 반환하고, 관련 함수도 훅으로 한 번 더 감싸서 컴포넌트에서는 정해진 함수명으로 호출하도록 해보았어요

2024-04-29 09:09 UTC, kjheee commented on src/hooks/services/queries/chat.ts
> +  useMessageByIdQuery(chatRoomId, messageId).data;
query 함수 관련하여 레이어를 한 번 더 감싸서 라이브러리 로직을 캡슐화하면 좋은 점에 대해 생각해 보았어요🤔
- 페칭 로직을 프레임워크에 의존하지 않고, 재사용성을 높인다.
		- 사용하는 곳에서는 훅이 어떤 라이브러리, 어떤 로직을 통해 값을 얻는지 알 필요 없이 반환된 값만 사용하면 된다.
		- 같은 값을 반환하면서 내부 로직에 변경사항이 생기더라도 컴포넌트 수정 없이 개선이 가능하다.

이렇게 생각했을 때, 바로 `useSuspenseQuery`를 훅으로 반환하는 방법과 이를 한 번 더 감싼 `useChatRoomQuery`를 반환하는 방법에서 큰 차이점을 찾지 못했는데 제가 놓친 부분이 있을까요??
```typescript
const useChatRoom = (chatRoomId:string) => useSuspenseQuery(chatRoomQueryOptions(chatRoomId)).data
const useChatRoom = (chatRoomId:string) => useChatRoomQuery(chatRoomId).data;

2024-04-29 09:09 UTC, kjheee commented on src/components/Chat/ChatRooms.tsx
> +            {renderModal()}
보통 context로 구현된 모달은 ModalProvider 아래 `{renderModal()}`과 같은 함수를 두어 배열에 추가된 모달을 전역에서 띄우고 stack처럼 관리해요!

그런데 현재 구현된 모달은 useModal 호출 시 `openModal, closeModal, rendeModal`이 동일한 `modalId`로 바인딩 되어 있고, useModal을 호출한 컴포넌트에 renderModal을 호출하여 openModal과 같은 id로 연결된 모달만을 렌더링하도록 설계되어 있어요. 대신 createPortal이 참조할 ref는 ModalProvider에 적용해 모달은 App 최상위에서 열립니다! 
그래서 renderModal 함수가 모달을 호출한 컴포넌트에서 선언되어야 하는 구조가 되었어요.

- 모달 관련해서 정리한 글이 있는데 전체 글은 길이가 조금 있어서 최종 완성 코드가 담긴 챕터의 글 링크를 첨부드려요! 
시간이 되신다면 한번 둘러봐주세요 😀
- https://heeheehoho.tistory.com/entry/modal-5

2024-05-06 14:42 UTC, bigsaigon333 commented on src/components/Chat/SidePanel/SidePanel.tsx
> +    }
코드가 엄청 깔끔해졌네요~~

2024-05-06 14:44 UTC, bigsaigon333 commented on src/components/Chat/ChatPanel/ChatPanel.tsx
> +    const messages$ = data.map((message) => <ChatMessage key={message.id} message={message} />);
rxjs 에서 Observable 변수에 suffix로 $를 추가하는 컨벤션이 있는데, 
혹시 요거를 참고하신건지 궁금했었어요 😄

2024-05-06 14:48 UTC, bigsaigon333 commented on src/components/Chat/ChatRooms.tsx
> +          onSuccess: (chatRoomId: string) => navigate(`/lines/${chatRoomId}`),
> mutate가 받는 인자를 넘겨서 onSuccess를 반환하도록 고민을 해보았는데 useMutation의 onSuccess 옵션을 반환하는 방법을 찾지 못했어요.. 대신 mutate의 2번째 인자 옵션을 활용해 컴포넌트 내에서 라우팅 로직을 처리할 수 있도록 해보았습니다!


`useCreateChatRoom` 이 현재 인자를 받지 않고 있는데, 
인자로 onSuccess, onError 등의 options를 받도록 한다면,
아래와 같이 사용할 수 있습니다 😄 

```tsx
  const { createChatRoom } = useCreateChatRoom({onSuccess: () => navigate(...));
```

그렇다면, 지금과 같이 mutate함수에서 onSuccess를 넣어주는 것과 어떤 차이가 있느냐... 는 숙제입니다 😄

2024-05-06 14:51 UTC, bigsaigon333 commented on src/components/Chat/ChatRooms.tsx
> +          onSuccess: (chatRoomId: string) => navigate(`/lines/${chatRoomId}`),
> mutate 함수를 별도 이름을 지정해 반환하고, 관련 함수도 훅으로 한 번 더 감싸서 컴포넌트에서는 정해진 함수명으로 호출하도록 해보았어요

훅으로 한번 더 감싸는건 좋아요! 근데, mutate를 createChatRoom 로 이름을 바꿔서 export 할 필요는 있을까 싶어요. 지금처럼 onSuccess, onError 등을 사용한다면, react-query의 useMutation 을 사용한다는게 너무 드러나서, 그냥 mutate로 내보내는 것이(useMutation의 반환값을 그대로 반환하는 것이) 더 일반적인거 같아요~

이것도 framework-agnostic 하게 쓰려면, `mutateAsync`와 같이 호출하면 promise를 반환하는 함수만을 반환해야하지 않을까 싶어요
(현업에서 그닥 많이 쓰이는 패턴은 아닌데.. 선호하시는 분도 있긴 합니다 😄 )

2024-05-06 14:53 UTC, bigsaigon333 commented on src/hooks/services/queries/chat.ts
> +  useMessageByIdQuery(chatRoomId, messageId).data;
`/* 2번 */ const useChatRoom = (chatRoomId:string) => useChatRoomQuery(chatRoomId).data;`
요 방법은 `queryOptions`를 사용하기 전에 많이 썼던 패턴인데, 

`queryOptions`를 사용하면서 
`/* 1번 */ const useChatRoom = (chatRoomId:string) => useSuspenseQuery(chatRoomQueryOptions(chatRoomId)).data`
요렇게 바로 쓰면 된다고 생각합니다 😄

2024-05-06 14:54 UTC, bigsaigon333 commented on src/hooks/services/queries/chat.ts
> +  });
아주 Gooooood 이에요 👍🏻 x 10000

2024-05-06 14:55 UTC, bigsaigon333 commented on src/hooks/services/mutations/chat.ts
> +      }),
```suggestion
      queryClient.invalidateQueries(messageQueryOptions(chatRoomId)),
```

queryOptions 정의해둔거 써먹어야죠~~

2024-05-06 14:56 UTC, bigsaigon333 commented on src/hooks/services/mutations/chat.ts
> +export const useAddMessage = useMessageMutation;
굳이 이름까지 바꿔가면 한번더 export 할 필요가 있을까용?

2024-05-06 14:57 UTC, bigsaigon333 commented on src/components/Chat/ChatPanel/ChatMessage/ChatMessage.tsx
> +  const timeAgo = moment(Number(message.timestamp)).format('HH:mm');
FYI) `moment`는 deprecated 되어서, 현업에서는 date-fns 또는 dayjs를  주로 사용합니다 😄

2024-05-06 14:58 UTC, bigsaigon333 commented on src/components/Chat/ChatPanel/ChatForm/ChatForm.tsx
> +          ></textarea>
```suggestion
          <textarea
            className={cx('text-input')}
            style={{ height: textareaHeight + 'px' }}
            {...register('content', {
              onChange: () => resizeTextareaHeight(getValues('content')),
            })}
            rows={1}
            onKeyDown={handleEnterSubmit}
            placeholder="내용을 입력해주세요"
            autoFocus
          />
```

사소하지만 요런것도 챙기는게 좋아용
기존과 같이 작성하면 children을 쓰려고 했는데 개발자가 실수로 깜빡한 것인지
children이 원래 없었던건지 알수가 없어서
개발자의 의도가 분명해지지 않는다는 단점이 있어요!

2024-05-06 22:55 UTC, bigsaigon333 commented on src/components/Chat/ChatRooms.tsx
> +            {renderModal()}
100% 이해하였다고 말할순 없지만.. 블로그를 보면서 생각한 점 크게 2가지 말씀드려볼게요!

1. 모달이 닫히는 타이밍이 너무 빠르다고 볼 수도 있을거 같아요

유저가 확인/닫기 를 누르는 것도 비동기이지만, 확인 버튼을 눌러서 api를 호출하는 것도 비동기인데요,
유저가 확인 버튼을 누르자마자 모달이 일단 닫히고 그 다음에 api를 호출하는데,
모달이 바로 닫혀버리니까 이 api를 호출하고 있다는 사실이 유저에게 잘 전달이 되지 않을거 같아요.
보통은 api를 호출중이면, 확인 버튼을 disabled 처리하고 로딩 인디케이터 같은걸 버튼에 붙이거든요.
로딩 인디케이터가 돌아가고 있으면,, 아 유저는 뭔가 실행중이어서 대기해야하는구나 라고 인지하는거 같아요.
그리고 일시적인 네트워크 장애 등으로 api 호출에 실패한다면, 모달에서 다시 한번 확인 버튼을 누를수 있어야 하는데
일단 닫혀버리니 불가능한거 같아요.
주저리주저리 썼는데, 모달이 닫히려면 자기의 역할이 다 끝나고 닫혀야 하는데, 저는 모달의 역할이 api 호출등의 비동기 처리까지 포함한다고 생각해요 😄  



```tsx
    const handleCreate = async () => {
        try {
            const chatRoomInfo = await openModal(CreateChatRoomModal);
            mutate({ user, chatRoomInfo });
        } catch (err) {
            console.log('모달 닫습니다~!');
        }
    };
```


2. `cloneElement` 사용을 좀 줄이는 방향으로 고민해보면 어떨까요?
`cloneElement`가 컴포넌트 생성 흐름이 명시적이지 않아서 react 18부터 사용을 자제하자고 공식문서에서도 얘기하고 있는데요,
꼭 필요하다면 당연히 써야겠지만, 다른 방법은 없을까? 같은 방향으로도 한번 고민해보셨으면 좋겠어서 언급드려봅니다!

https://react.dev/reference/react/cloneElement


3. `{renderModal()}` 말고 `<ModalContainer />` 와 같이 쓰면 어떨까요?
함수 호출과 컴포넌트로 생성후 jsx로 표기하는 것은 어떤 차이가 있는지도 한번 생각해보셨으면 좋겠어요 😄

2024-05-08 04:11 UTC, kjheee reviewed
피드백을 적용하여 전체적으로 개선해보았어요 😀
- `date-fns` 라이브러리 적용
- `cloneElement`를 `createElemet`로 변경
    - 복제보다는 modal state에 저장된 컴포넌트를 이용해 독립적인 element를 생성하는 것이 더 좋을 것 같다고 생각해 변경했습니다!

2024-05-08 04:11 UTC, kjheee commented on src/components/Chat/ChatPanel/ChatForm/ChatForm.tsx
> +          ></textarea>
다른 사람이 작성한 코드를 읽을때도 생각해볼 수 있는 부분이네요!👍

2024-05-08 04:11 UTC, kjheee commented on src/hooks/services/queries/chat.ts
> +  useMessageByIdQuery(chatRoomId, messageId).data;
너무 좋습니다✨

2024-05-09 01:46 UTC, bigsaigon333 approved these changes
정희님 고생하셨습니다~~

`createElement` 쓴 부분에 대해서만 추가 코멘트 남겼으니 확인 부탁드려요!
수정은 다음에 시간 되실 때 한번 시도해보셨으면 좋겠습니다~


이제 다음 기능구현으로 넘어가시죠 👍🏻👍🏻👍🏻👍🏻👍🏻

2024-05-09 01:46 UTC, bigsaigon333 commented on src/components/@common/Modal/Modal.tsx
> +  return <>{createElement(element.type, { onSubmit: resolve, onAbort: reject })}</>;
modal에서 element를 전달받지 않고, Component를 전달받아

`<Component onSubmit={resolve} onAbort={reject} />` 와 같은식으로 하는건 어떤가요?

`createElement`도 명령적으로 Component를 element로 생성한다는 점에서 cloneElement과 동일한  단점을  가지고 있다고 생각해요!

2024-05-09 03:25 UTC, kjheee commented on src/components/@common/Modal/Modal.tsx
> +  return <>{createElement(element.type, { onSubmit: resolve, onAbort: reject })}</>;
더 안전한 방법으로 개선해볼게요! 😁😁

2024-05-09 03:29 UTC, merged